# Site
repository: sorenlaney/laney_s_resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Soren Laney
title: CFO Laney Media
email: soren@laneymedia.org
website: www.github.com/sorenlaney/laney_s_resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: Soren_Laney_
github_username:  sorenlaney
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: soren.laney
linkedin_username: 'Soren Laney'
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: sorenlaney9847
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: laneymedia.org
  icon: fas fa-globe
  url: https://laneymedia.org/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Soren and I am the CFO at Laney Media, a business consulting company. As well as being a CFO, I am a data scientist and analyst for catalyzing online business growth. 

  I am most skilled in: <mark>Python</mark>, <mark>PySpark</mark>, <mark>R</mark>, <mark>SQL</mark>, <mark>DAX</mark>  & <mark>VBA</mark> 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Orenco Composites Inc.
        link: https://www.orenco.com/
        # link_text: https://www.orenco.com/
        sub_title: Draftsman I
        caption: June 2015 - April 2017
        quote: >
          Orenco researches, designs, and manufactures innovative onsite, low maintenance, decentralized wastewater collection and treatment technologies.
        description: | # this will include new lines to allow paragraphs
            I worked as a draftsman converting the companies current technical drawings into  their new system while adding new products at the same time. This required working in conjunction with multiple departments to successfully facilitate this change. 

      # - layout: left
      #   title: Aptive 
      #   link: https://www.goaptive.com/
      #   # link_text: https://www.goaptive.com/
      #   sub_title: Sales Team Leader
      #   caption: April 2019 - June 2021
      #   quote: >
      #     Aptive Environmental provides effective pest solutions solutions to protect your home from pests. Call today!
      #   description: | # this will include new lines to allow paragraphs
      #       I lead a Sales team that generated over a quarter million dollars in ARR over a 3 month timespan. 


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Brigham Young University - Idaho
        caption: 2019-2022
        sub_title: BSc Data Science & Finance
        quote: >
          On November 12, 1888, The Church of Jesus Christ of Latter-day Saints created Bannock Stake Academy in Rexburg, Idaho. In 1903, the school was renamed again as Ricks Academy in honor of Thomas E. Ricks, the Bannock Stake president at the time it was founded and the chairman of the school's first Board of Education.
        description: | # this will include new lines to allow paragraphs
          During my time at BYU-I I learned an indepth understanding of the data science process and data analysis.  

          I spent most of time developing skills in relation to entrepreneurship such as sales psychology and marketing.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Ultra Running
      - Ironmans
      - Skiing
      



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
